##############################################################################
# Automations and required components to configure colors on the HASP panel
#
# Check out this site for easy color code selection and conversion:
# https://nodtem66.github.io/nextion-hmi-color-convert/index.html

input_number:
  hasp_plate01_selectedforegroundcolor:
    name: plate01 Selected Foreground Color
    icon: mdi:palette
    min: 0
    max: 65535
    step: 1
    mode: box
  hasp_plate01_selectedbackgroundcolor:
    name: plate01 Selected Background Color
    icon: mdi:palette
    min: 0
    max: 65535
    step: 1
    mode: box
  hasp_plate01_unselectedforegroundcolor:
    name: plate01 Unselected Foreground Color
    icon: mdi:palette
    min: 0
    max: 65535
    step: 1
    mode: box
  hasp_plate01_unselectedbackgroundcolor:
    name: plate01 Unselected Background Color
    icon: mdi:palette
    min: 0
    max: 65535
    step: 1
    mode: box
group:
  plate01_colors:
    name: plate01 Colors
    entities:
      - input_number.hasp_plate01_selectedforegroundcolor
      - input_number.hasp_plate01_selectedbackgroundcolor
      - input_number.hasp_plate01_unselectedforegroundcolor
      - input_number.hasp_plate01_unselectedbackgroundcolor
