##############################################################################
# Automations to set colors on HASP Page 4
#
# Here we've swapped selected/unselected as these buttons will always be
# unselected (unless actively being pressed), and sliders do not have a
# selected/unselected state.
automation:
  - alias: hasp_plate01_p4_ColorConfig
    trigger:
    - platform: state
      entity_id: 'binary_sensor.plate01_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_number.hasp_plate01_selectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_unselectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_selectedforegroundcolor
    - platform: state
      entity_id: input_number.hasp_plate01_unselectedforegroundcolor
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/json'
        payload_template: >-
          [{%- for i in range(4,7) -%}"p[4].b[{{i}}].pco={{ states.input_number.hasp_plate01_selectedforegroundcolor.state|int }}",{%- endfor -%}
          {%- for i in range(4,7) -%}"p[4].b[{{i}}].bco={{ states.input_number.hasp_plate01_selectedbackgroundcolor.state|int }}",{%- endfor -%}
          {%- for i in range(4,7) -%}"p[4].b[{{i}}].pco2={{ states.input_number.hasp_plate01_unselectedforegroundcolor.state|int }}",{%- endfor -%}
          {%- for i in range(4,7) -%}"p[4].b[{{i}}].bco2={{ states.input_number.hasp_plate01_unselectedbackgroundcolor.state|int }}"{% if not loop.last %},{% endif %}{%- endfor -%}]
    - service: mqtt.publish
      data:
        topic: 'hasp/plate01/command/json'
        payload_template: >-
          [{%- for i in range(7,10) -%}"p[4].b[{{i}}].pco={{ states.input_number.hasp_plate01_unselectedforegroundcolor.state|int }}",{%- endfor -%}
          {%- for i in range(7,10) -%}"p[4].b[{{i}}].bco={{ states.input_number.hasp_plate01_unselectedbackgroundcolor.state|int }}"{% if not loop.last %},{% endif %}{%- endfor -%}]